# Generated by Django 2.0.1 on 2018-01-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knuapp', '0008_auto_20180201_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announ_natural',
        ),
    ]
