# Generated by Django 2.0.1 on 2018-02-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knuapp', '0010_announ_ame_announ_archeng_announ_archi_announ_civil_announ_control_announ_cse_announ_ie_announ_mech_'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announ_earth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='lasted',
            field=models.CharField(default='18-02-02', max_length=128),
        ),
    ]
